packages:
- location: lib/hashtables
  extra-dep: true
- location: galua
- location: galua-dbg
- location: galua-analysis
- location: galua-spec
- location: lib/dwarf-tools
- location: lib/language-lua
resolver: lts-7.11
extra-deps:
- config-value-0.5
- config-value-getopt-0.1.0.0
- elf-0.27
- lua-bc-0.1.0.2
- alex-tools-0.1.1.0
