packages:
- location: lib/hashtables
  extra-dep: true
- location: galua
- location: galua-dbg
- location: galua-analysis
- location: lib/dwarf-tools
resolver: lts-6.14
extra-deps:
- config-value-0.5
- config-value-getopt-0.1.0.0
- elf-0.27
- lua-bc-0.1.0.1
- language-lua-0.10.0
