packages:
- location: lib/hashtables
  extra-dep: true
- location: galua
- location: galua-dbg
- location: galua-analysis
resolver: lts-6.9
extra-deps:
- language-lua-0.9.0
- config-value-0.4.0.2
- config-value-getopt-0.1.0.0
- lua-bc-0.1
