packages:
- location: lib/hashtables
  extra-dep: true
- location: galua-rts
- location: galua
- location: galua-dbg
- location: galua-analysis
- location: galua-spec
- location: lib/dwarf-tools
- location: lib/language-lua
- location: https://github.com/yav/dump-core/archive/master.zip
  extra-dep: true

resolver: lts-8.13
extra-deps:
- config-value-0.5
- config-value-getopt-0.1.0.0
- elf-0.27
- alex-tools-0.1.1.0
- lua-bc-0.1.1

flags:
  galua:
    dump-core: false
  galua-dbg:
    dump-core: false
