packages:
- location: lib/hashtables
  extra-dep: true
- location: galua
- location: galua-dbg
- location: galua-analysis
- location: lib/dwarf-tools
- location: lib/language-lua
resolver: lts-6.12
extra-deps:
- config-value-0.5
- config-value-getopt-0.1.0.0
- lua-bc-0.1
- elf-0.27
