system-ghc: false

packages:
- location: lib/hashtables
  extra-dep: true
- location: galua-rts
- location: galua-jit
- location: galua
- location: galua-dbg
- location: galua-spec
- location: lib/dwarf-tools
- location: lib/language-lua
- location: lib/lua-bc
- location: https://github.com/yav/dump-core/archive/master.zip
  extra-dep: true

resolver: lts-9.0
extra-deps:
- config-value-0.5
- config-value-getopt-0.1.0.0
- elf-0.27
- alex-tools-0.3
- lua-bc-0.1.1
- GraphSCC-1.0.4
- monadLib-3.7.3


flags:
  galua:
    dump-core: false
  galua-dbg:
    dump-core: false
